safe: true
auto: true
source: ./
destination: ./_site
lsi: false
pygments: true
markdown: redcloth
permalink: none
url: http://donkeylucky.github.io

name: donkeylucky
title: donkeylucky Blog
author: donkeylucky
email: tweegdong@gmail.com
